client_config_backend: settings
client_config:
  client_id: 194929262698-1r47m9hub5h8c6ormaqlj3p9nqfhs068.apps.googleusercontent.com
  client_secret: 1MJe-YX4_A0oQ6LNc0oQKOmh

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install