client_config_backend: settings
client_config:
  client_id: 500096382553-tj60a486ebe4u9fsgjc3lchgls373uoo.apps.googleusercontent.com
  client_secret: wI4SpdlZqoE2muexVwwI4HRR

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install